import puppeteer from 'puppeteer-core';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const url='file:///Users/future/Desktop/TAIL.TRADE%20Gitbook/matchday-gates/videos/06-gate-run.html';
const HARNESS=()=>{const rSI=setInterval.bind(window),rCI=clearInterval.bind(window);
 const C={vt:0,rafs:[],timers:[],id:1,ready:false,errs:[]};window.__cap=C;
 performance.now=()=>C.vt;const RD=Date;window.Date=class extends RD{constructor(...a){a.length?super(...a):super(17e11+C.vt);}static now(){return 17e11+C.vt;}};
 window.requestAnimationFrame=cb=>{C.rafs.push(cb);return C.rafs.length;};window.cancelAnimationFrame=()=>{};
 window.setTimeout=(fn,d=0,...a)=>{const id=C.id++;C.timers.push({id,due:C.vt+Math.max(0,d),fn,a,every:0});return id;};
 window.setInterval=(fn,d=0,...a)=>{const id=C.id++;C.timers.push({id,due:C.vt+Math.max(1,d),fn,a,every:Math.max(1,d)});return id;};
 window.clearTimeout=window.clearInterval=id=>{C.timers=C.timers.filter(t=>t.id!==id);};
 window.__pump=dt=>{const tg=C.vt+dt;let g=0;while(g++<5000){const t=C.timers.filter(x=>x.due<=tg).sort((a,b)=>a.due-b.due)[0];if(!t)break;C.vt=t.due;try{t.fn(...t.a);}catch(e){C.errs.push('timer:'+e.message);}if(t.every)t.due+=t.every;else C.timers=C.timers.filter(x=>x!==t);}C.vt=tg;const q=C.rafs;C.rafs=[];for(const cb of q){try{cb(C.vt);}catch(e){C.errs.push('raf:'+(e.stack||e.message).split('\n').slice(0,2).join(' | '));}}};
 const a=rSI(()=>{window.__pump(1000/60);if(window.__READY__&&!C.ready){C.ready=true;rCI(a);}},1000/60);};
const b=await puppeteer.launch({executablePath:CHROME,headless:true,args:['--enable-unsafe-swiftshader','--hide-scrollbars']});
const p=await b.newPage();await p.evaluateOnNewDocument(HARNESS);await p.setViewport({width:1920,height:1080});
await p.goto(url,{waitUntil:'domcontentloaded'});await p.waitForFunction('window.__READY__===true',{timeout:8000}).catch(()=>{});
await p.evaluate(()=>{for(let t=0;t<15000;t+=1000/30)window.__pump(1000/30);});
await p.evaluate(()=>{for(let i=0;i<150;i++)window.__pump(1000/30);});
const r=await p.evaluate(()=>{const cv=document.querySelector('canvas');const x=cv.getContext('2d');let nz=0;try{const d=x.getImageData(0,0,cv.width,cv.height).data;for(let i=0;i<d.length;i+=4)if(d[i]>40||d[i+1]>40||d[i+2]>40)nz++;}catch(e){return{err:'getImageData:'+e.message};}return{errs:[...new Set(window.__cap.errs)].slice(0,4),brightPixels:nz,vt:Math.round(window.__cap.vt),rafsPending:window.__cap.rafs.length};});
console.log(JSON.stringify(r,null,2));await b.close();
